### ISSUE TITLE
Left Click Button

### ISSUE THREAD

**Issue by ogustavo-pereira** [felipemendes/minimal-stack-overflow#1]
Hi, I like this extension!

I think it would be better add left click button event for open the menu or for minify the content.

:smile:

**Comment by felipemendes** [comment]
Hey, @oguhpereira. Thank you :+1:
I'm not sure what you mean about left click event. The 'Show Details' button on top already trigges this event to display sidebars. That's what you means?

![screen shot 2019-02-13 at 19 48 51](https://user-images.githubusercontent.com/3712089/52746653-2b209b80-2fc9-11e9-9fd6-b3b283f0dc05.png)

**Comment by ogustavo-pereira** [comment]
Left Click on Extension icon
![image](https://user-images.githubusercontent.com/24482087/52748411-98cec680-2fcd-11e9-9a19-b2aad3ee3514.png)

**Comment by felipemendes** [comment]
I got you. I'll try to add this feature.
Thanks!
